### PR TITLE
Implement PEP 8 compliance using flake8

### PR DESCRIPTION
**Pull request by MarkusHackspacher**
#18 
add file .flake8
add CI test at .github
add requirements.txt
pep8 changes arg_parser.py

### CODE REVIEW

**Comment by ariel-frischer** [comment]
Hey @MarkusHackspacher thanks for making this pull request, is this automated? Curious what tech your using to automate these PRs.

**Comment by MarkusHackspacher** [comment]
The script  .github/workflows/python-app.yml is from github, you can find it in "Actions" --> new workflow -->
select this:
Python application
By GitHub Actions
Python application logo
Create and test a Python application.

and configure and PR. I make no changes at this script.

**Comment by MarkusHackspacher** [comment]
@ariel-frischer have you other questions? And if you decide to merge this PR, could you add the “hacktoberfest-accepted” label?

**Comment by ariel-frischer** [comment]
@MarkusHackspacher 
Sorry the issue I made for this repo was just some auto-generated issue for testing purposes. I don't really want to implement flake8 for this repo although it may help. I do not want to go through the whole process of testing this out and refactoring/confirming all the flake8 changes either. So I'm going to close this out, sorry about the misunderstanding I will remove the flake8 issue as well.

**Pull request closed without merging**
